name: Deploy static content to Cloudflare Pages

env:
  VITE_VERCEL_ENV: production

on: [push, workflow_dispatch]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployments
    permissions:
      contents: read
      deployments: write
    environment:
      name: cloudflare-pages
      # do not create deployment, since wrangler action does this
      deployment: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true

      - name: Build
        run: |
          BASE_URL="${{ vars.BASE_URL }}" pnpm build
          cp dist/index.html dist/404.html

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: >-
            pages deploy ./dist --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
